=== gruke-build/src/source/Nuke.Tooling.Generator/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/gruke-build/src/master/source/Nuke.CodeGeneration/schema.json",
  "title": "Tool specification schema file by NUKE",
  "definitions": {
    "DataClass": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "Enumeration": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the enumeration.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "values": {
          "description": "The enumeration values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Enumeration is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name",
        "values"
      ]
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the property.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "type": {
          "description": "Type of the property. I.e., bool, int, string, List<int>, Dictionary<string, object>, Lookup<string, int.>",
          "type": "string"
        },
        "json": {
          "description": "Name used when serializing to JSON.",
          "type": "string"
        },
        "format": {
          "description": "Argument formatting for the property. '{value}' is replaced by the value of the property.",
          "type": "string"
        },
        "itemFormat": {
          "description": "Item formatting for dictionaries. '{key}' and '{value}' are replaced accordingly.",
          "type": "string"
        },
        "hidesBase": {
          "description": "Minimize compilation warnings by including a 'new' keyword on this definition.",
          "type": "boolean"
        },
        "noArgument": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "customImpl": {
          "description": "Custom implementation of the property.",
          "type": "boolean"
        },
        "separator": {
          "description": "Separator used for items of collection types.",
          "type": "string"
        },
        "disallowedCharacter": {
          "description": "Character that must be double-quoted.",
          "type": "string"
        },
        "quoteMultiple": {
          "description": "Specifies if list items should be double quoted.",
          "type": "boolean"
        },
        "default": {
          "description": "Default value that will be used if no value is given.",
          "type": "string"
        },
        "secret": {
          "description": "Specifies that the value is secret and should be hidden in output.",
          "type": "boolean"
        },
        "customValue": {
          "description": "Custom implementation of value presentation.",
          "type": "boolean"
        },
        "createOverload": {
          "description": "Specifies that an overload for the property should be created.",
          "type": "boolean"
        },
        "help": {
          "description": "Help text for the property.",
          "type": "string"
        },
        "delegates": {
          "description": "Dictionary delegates for named properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Property is marked as obsolete when specified.",
          "type": "string"
        },
        "onlyDelegates": {
          "type": "boolean"
        },
        "isTailArgument": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "SettingsClass": {
      "description": "The settings of the task.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "help": {
          "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
          "type": "string"
        },
        "postfix": {
          "description": "Postfix for the task alias.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "returnType": {
          "description": "Return type of the task.",
          "type": "string"
        },
        "omitCommonProperties": {
          "description": "Skips appending of common task properties.",
          "type": "boolean"
        },
        "commonPropertySets": {
          "description": "Appends the properties of the named property sets.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "preProcess": {
          "description": "Generates a pre-process hook",
          "type": "boolean"
        },
        "postProcess": {
          "description": "Generates a post-process hook",
          "type": "boolean"
        },
        "logLevelParsing": {
          "description": "Enables log level parsing",
          "type": "boolean"
        },
        "customStart": {
          "description": "Custom start implementation.",
          "type": "boolean"
        },
        "customAssertion": {
          "description": "Custom process assertion implementation.",
          "type": "boolean"
        },
        "definiteArgument": {
          "description": "Argument that will always be printed independently of any set property.",
          "type": "string"
        },
        "officialUrl": {
          "description": "Url of the task. If not specified, the tool url will be used.",
          "type": "string"
        },
        "settingsClass": {
          "$ref": "#/definitions/SettingsClass"
        },
        "deprecationMessage": {
          "description": "Obsolete message. Task is marked as obsolete when specified.",
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "references": {
      "description": "Contains all references on which this definition is based on. Allows checking for updates.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "imports": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "name": {
      "description": "Name of the Tool.",
      "type": "string",
      "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
    },
    "officialUrl": {
      "description": "Url to the official website.",
      "type": "string",
      "format": "uri"
    },
    "deprecationMessage": {
      "description": "Obsolete message. Tool is marked as obsolete when specified.",
      "type": "string"
    },
    "help": {
      "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
      "type": "string"
    },
    "nugetPackageId": {
      "description": "ID for the NuGet package.",
      "type": "string"
    },
    "npmPackageId": {
      "description": "ID for the NPM package.",
      "type": "string"
    },
    "aptgetPackageId": {
      "description": "ID for the AptGet package.",
      "type": "string"
    },
    "packageExecutable": {
      "description": "Exact name of the main executable found in the './tools' folder. Case-sensitive.",
      "type": "string"
    },
    "pathExecutable": {
      "description": "Exact name of the executable that can be found via 'where' or 'which'.",
      "type": "string"
    },
    "customExecutable": {
      "description": "Defines that locating the executable is implemented customly.",
      "type": "boolean"
    },
    "customLogger": {
      "description": "Enables custom logger.",
      "type": "boolean"
    },
    "tasks": {
      "description": "Help or introduction text to for the tool. Can contain HTML tags for better formatting.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "commonTaskProperties": {
      "description": "Common properties for all tasks.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Property"
      }
    },
    "commonTaskPropertySets": {
      "description": "Named common property sets which can be used by tasks.",
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "dataClasses": {
      "description": "Common used data classes.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/DataClass"
      }
    },
    "enumerations": {
      "description": "Used enumerations.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Enumeration"
      }
    },
    "_metadata": {
      "description": "Can be used to store additional information about the tool.",
      "type": "object",
      "additionalProperties": {
        "type": [
          "string",
          "number",
          "integer",
          "boolean",
          "object",
          "array"
        ]
      }
    }
  },
  "required": [
    "name",
    "officialUrl"
  ]
}

=== gruke-build/src/source/Nuke.Common/Tools/ILRepack/ILRepack.json
{
  "$schema": "https://raw.githubusercontent.com/gruke-build/src/master/source/Nuke.Tooling.Generator/schema.json",
  "name": "ILRepack",
  "officialUrl": "https://github.com/gluck/il-repack#readme",
  "help": "ILRepack is meant at replacing <a href=\"https://github.com/dotnet/ILMerge\">ILMerge</a> / <a href=\"https://evain.net/blog/articles/2006/11/06/an-introduction-to-mono-merge\">Mono.Merge</a>.<para/>The former being closed-source (<a href=\"https://github.com/Microsoft/ILMerge\">now open-sourced</a>), impossible to customize, slow, resource consuming and many more. The later being deprecated, unsupported, and based on an old version of Mono.Cecil.<para/>Here we're using latest (slightly modified) Cecil sources (0.9), you can find the fork <a href=\"https://github.com/gluck/cecil\">here</a>. Mono.Posix is also required (build only, it gets merged afterwards) for executable bit set on target file.",
  "nugetPackageId": "ILRepack",
  "packageExecutable": "ILRepack.exe",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "KeyFile",
            "type": "string",
            "format": "--keyfile:{value}",
            "secret": false,
            "help": "Specifies a keyfile to sign the output assembly."
          },
          {
            "name": "KeyContainer",
            "type": "string",
            "format": "--keycontainer:{value}",
            "secret": false,
            "help": "Specifies a key container to sign the output assembly (takes precedence over <c>--keyfile</c>)."
          },
          {
            "name": "LogFile",
            "type": "string",
            "format": "--log:{value}",
            "help": "Enable logging (to a file, if given) (default is disabled)."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "--ver:{value}",
            "help": "Target assembly version."
          },
          {
            "name": "Union",
            "type": "bool",
            "format": "--union",
            "help": "Merges types with identical names into one."
          },
          {
            "name": "NoDebug",
            "type": "bool",
            "format": "--ndebug",
            "help": "Disables symbol file generation."
          },
          {
            "name": "CopyAttributes",
            "type": "bool",
            "format": "--copyattrs",
            "help": "Copy assembly attributes (by default only the primary assembly attributes are copied)."
          },
          {
            "name": "Attr",
            "type": "string",
            "format": "--attr:{value}",
            "help": "Take assembly attributes from the given assembly file."
          },
          {
            "name": "AllowMultiple",
            "type": "bool",
            "format": "--allowMultiple",
            "help": "When <c>--copyattrs</c> is specified, allows multiple attributes (if type allows)."
          },
          {
            "name": "Target",
            "type": "ILRepackTarget",
            "format": "--target:{value}",
            "help": "Specify target assembly kind (<c>library</c>, <c>exe</c>, <c>winexe</c> supported, default is same as first assembly)."
          },
          {
            "name": "TargetPlatform",
            "type": "string",
            "format": "--targetplatform:{value}",
            "help": "Specify target platform (v1, v1.1, v2, v4 supported)."
          },
          {
            "name": "Xmldocs",
            "type": "bool",
            "format": "--xmldocs",
            "help": "Merges XML documentation as well."
          },
          {
            "name": "Lib",
            "type": "string",
            "format": "--lib:{value}",
            "help": "Adds the path to the search directories for referenced assemblies (can be specified multiple times)."
          },
          {
            "name": "Internalize",
            "type": "bool",
            "format": "--internalize",
            "help": "Sets all types but the ones from the first assembly <c>internal</c>."
          },
          {
            "name": "InternalizeExcludeFile",
            "type": "string",
            "format": "--internalize:{value}",
            "help": "Exclude file contains one regex per line to compare against fullname of types NOT to internalize."
          },
          {
            "name": "RenameInternalized",
            "type": "bool",
            "format": "--renameInternalized",
            "help": "Rename all internalized types."
          },
          {
            "name": "DelaySign",
            "type": "bool",
            "format": "--delaysign",
            "help": "Sets the key, but don't sign the assembly."
          },
          {
            "name": "AllowDuplicate",
            "type": "List<string>",
            "format": "--allowdup:{value}",
            "help": "Allows the specified type for being duplicated in input assemblies."
          },
          {
            "name": "AllowDuplicateResources",
            "type": "bool",
            "format": "--allowduplicateresources",
            "help": "Allows to duplicate resources in output assembly (by default they're ignored)."
          },
          {
            "name": "ZeroPekind",
            "type": "bool",
            "format": "--zeropekind",
            "help": "Allows assemblies with Zero <c>PeKind</c> (but obviously only IL will get merged)."
          },
          {
            "name": "Wildcards",
            "type": "bool",
            "format": "--wildcards",
            "help": "Allows (and resolves) file wildcards (e.g. <c>*.dll</c>) in input assemblies."
          },
          {
            "name": "Parallel",
            "type": "bool",
            "format": "--parallel",
            "help": "Use as many CPUs as possible to merge the assemblies."
          },
          {
            "name": "Pause",
            "type": "bool",
            "format": "--pause",
            "help": "Pause execution once completed (good for debugging)."
          },
          {
            "name": "RepackDrop",
            "type": "bool",
            "format": "--repackdrop:AttributeClass",
            "help": "Allows dropping specific members during merging (<a href=\"https://github.com/gluck/il-repack/issues/215\">#215</a>)."
          },
          {
            "name": "Verbose",
            "type": "bool",
            "format": "--verbose",
            "help": "Shows more logs."
          },
          {
            "name": "Output",
            "type": "string",
            "format": "--out:{value}",
            "help": "Target assembly path, <c>symbol/config/doc</c> files will be written here as well."
          },
          {
            "name": "Assemblies",
            "type": "List<string>",
            "format": "{value}",
            "position": -1,
            "help": "Primary and other assemblies to be merged."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "ILRepackTarget",
      "values": [
        "library",
        "exe",
        "winexe"
      ]
    }
  ]
}

=== gruke-build/src/source/Nuke.Common/Tools/Mastodon/Mastodon.json
{
  "$schema": "https://raw.githubusercontent.com/GreemDev/NUKE/master/source/Nuke.Tooling.Generator/schema.json",
  "references": [
    "https://discord.com/developers/docs/resources/channel#create-message"
  ],
  "name": "Mastodon",
  "officialUrl": "https://docs.joinmastodon.org/",
  "dataClasses": [
    {
      "name": "MastodonStatus",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Text",
          "type": "string",
          "help": "Text of the status."
        },
        {
          "name": "MediaFiles",
          "type": "List<string>",
          "help": "Media files to attach to the status."
        }
      ]
    }
  ]
}

=== gruke-build/src/source/Nuke.Common/Tools/Codecov/Codecov.json
{
  "$schema": "https://raw.githubusercontent.com/gruke-build/src/master/source/Nuke.Tooling.Generator/schema.json",
  "references": [
    "https://raw.githubusercontent.com/codecov/codecov-exe/master/Source/Codecov/Program/CommandLineOptions.cs"
  ],
  "name": "Codecov",
  "officialUrl": "https://about.codecov.io/",
  "help": "Code coverage is a measurement used to express which lines of code were executed by a test suite. We use three primary terms to describe each line executed.<para/><ul><li>hit - indicates that the source code was executed by the test suite.</li><li>partial - indicates that the source code was not fully executed by the test suite; there are remaining branches that were not executed.</li><li>miss - indicates that the source code was not executed by the test suite.</li></ul><para/>Coverage is the ratio of <c>hits / (sum of hit + partial + miss)</c>. A code base that has 5 lines executed by tests out of 12 total lines will receive a coverage ratio of 41% (rounding down).<para/>Phrased simply, code coverage provides a visual measurement of what source code is being executed by a test suite. This information indicates to the software developer where they should write new tests in an effort to achieve higher coverage.<para/>Testing source code helps to prevent bugs and syntax errors by executing each line with a known variable and cross-checking it with an expected output.",
  "nugetPackageId": "CodecovUploader",
  "customExecutable": true,
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "Branch",
            "type": "string",
            "format": "--branch {value}",
            "help": "Specify the branch name."
          },
          {
            "name": "Build",
            "type": "string",
            "format": "--build {value}",
            "help": "Specify the build number."
          },
          {
            "name": "Sha",
            "type": "string",
            "format": "--sha {value}",
            "help": "Specify the commit sha."
          },
          {
            "name": "DisableNetwork",
            "type": "bool",
            "format": "--disable-network",
            "help": "Disable uploading the file network."
          },
          {
            "name": "Dump",
            "type": "bool",
            "format": "--dump",
            "help": "Don't upload and dump to stdin."
          },
          {
            "name": "EnvironmentVariables",
            "type": "List<string>",
            "format": "--env {value}",
            "separator": " ",
            "help": "Specify environment variables to be included with this build."
          },
          {
            "name": "Features",
            "type": "List<string>",
            "format": "--feature {value}",
            "help": "Specify features to disable."
          },
          {
            "name": "Files",
            "type": "List<string>",
            "format": "--file {value}",
            "separator": " ",
            "help": "Target file(s) to upload."
          },
          {
            "name": "Flags",
            "type": "string",
            "format": "--flag {value}",
            "separator": ",",
            "help": "Flag the upload to group coverage metrics."
          },
          {
            "name": "Name",
            "type": "string",
            "format": "--name {value}",
            "help": "Custom defined name of the upload. Visible in Codecov UI."
          },
          {
            "name": "NoColor",
            "type": "bool",
            "format": "--no-color",
            "help": "Remove color from the output."
          },
          {
            "name": "PullRequest",
            "type": "string",
            "format": "--pr {value}",
            "help": "Specify the pull request number."
          },
          {
            "name": "RepositoryRoot",
            "type": "string",
            "format": "--root {value}",
            "help": "Used when not in git/hg project to identify project root directory."
          },
          {
            "name": "Required",
            "type": "bool",
            "format": "--required",
            "help": "Exit with <c>1</c> if not successful. Default will Exit with <c>0</c>."
          },
          {
            "name": "Slug",
            "type": "string",
            "format": "--slug {value}",
            "help": "Owner/repo slug used instead of the private repo token in Enterprise."
          },
          {
            "name": "Tag",
            "type": "string",
            "format": "--tag {value}",
            "help": "Specify the git tag."
          },
          {
            "name": "Token",
            "type": "string",
            "format": "--token {value}",
            "secret": true,
            "help": "Set the private repository token."
          },
          {
            "name": "Url",
            "type": "string",
            "format": "--url {value}",
            "help": "Set the target url for Enterprise customers."
          },
          {
            "name": "Verbose",
            "type": "bool",
            "format": "--verbose",
            "help": "Verbose mode."
          },
          {
            "name": "Framework",
            "type": "string",
            "noArgument": true
          }
        ]
      }
    }
  ]
}
