=== gruke-build/src/source/Nuke.Tooling.Generator/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/gruke-build/src/master/source/Nuke.CodeGeneration/schema.json",
  "title": "Tool specification schema file by NUKE",
  "definitions": {
    "DataClass": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "Enumeration": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the enumeration.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "values": {
          "description": "The enumeration values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Enumeration is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name",
        "values"
      ]
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the property.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "type": {
          "description": "Type of the property. I.e., bool, int, string, List<int>, Dictionary<string, object>, Lookup<string, int.>",
          "type": "string"
        },
        "json": {
          "description": "Name used when serializing to JSON.",
          "type": "string"
        },
        "format": {
          "description": "Argument formatting for the property. '{value}' is replaced by the value of the property.",
          "type": "string"
        },
        "itemFormat": {
          "description": "Item formatting for dictionaries. '{key}' and '{value}' are replaced accordingly.",
          "type": "string"
        },
        "hidesBase": {
          "description": "Minimize compilation warnings by including a 'new' keyword on this definition.",
          "type": "boolean"
        },
        "noArgument": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "customImpl": {
          "description": "Custom implementation of the property.",
          "type": "boolean"
        },
        "separator": {
          "description": "Separator used for items of collection types.",
          "type": "string"
        },
        "disallowedCharacter": {
          "description": "Character that must be double-quoted.",
          "type": "string"
        },
        "quoteMultiple": {
          "description": "Specifies if list items should be double quoted.",
          "type": "boolean"
        },
        "default": {
          "description": "Default value that will be used if no value is given.",
          "type": "string"
        },
        "secret": {
          "description": "Specifies that the value is secret and should be hidden in output.",
          "type": "boolean"
        },
        "customValue": {
          "description": "Custom implementation of value presentation.",
          "type": "boolean"
        },
        "createOverload": {
          "description": "Specifies that an overload for the property should be created.",
          "type": "boolean"
        },
        "help": {
          "description": "Help text for the property.",
          "type": "string"
        },
        "delegates": {
          "description": "Dictionary delegates for named properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Property is marked as obsolete when specified.",
          "type": "string"
        },
        "onlyDelegates": {
          "type": "boolean"
        },
        "isTailArgument": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "SettingsClass": {
      "description": "The settings of the task.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "help": {
          "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
          "type": "string"
        },
        "postfix": {
          "description": "Postfix for the task alias.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "returnType": {
          "description": "Return type of the task.",
          "type": "string"
        },
        "omitCommonProperties": {
          "description": "Skips appending of common task properties.",
          "type": "boolean"
        },
        "commonPropertySets": {
          "description": "Appends the properties of the named property sets.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "preProcess": {
          "description": "Generates a pre-process hook",
          "type": "boolean"
        },
        "postProcess": {
          "description": "Generates a post-process hook",
          "type": "boolean"
        },
        "logLevelParsing": {
          "description": "Enables log level parsing",
          "type": "boolean"
        },
        "customStart": {
          "description": "Custom start implementation.",
          "type": "boolean"
        },
        "customAssertion": {
          "description": "Custom process assertion implementation.",
          "type": "boolean"
        },
        "definiteArgument": {
          "description": "Argument that will always be printed independently of any set property.",
          "type": "string"
        },
        "officialUrl": {
          "description": "Url of the task. If not specified, the tool url will be used.",
          "type": "string"
        },
        "settingsClass": {
          "$ref": "#/definitions/SettingsClass"
        },
        "deprecationMessage": {
          "description": "Obsolete message. Task is marked as obsolete when specified.",
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "references": {
      "description": "Contains all references on which this definition is based on. Allows checking for updates.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "imports": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "name": {
      "description": "Name of the Tool.",
      "type": "string",
      "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
    },
    "officialUrl": {
      "description": "Url to the official website.",
      "type": "string",
      "format": "uri"
    },
    "deprecationMessage": {
      "description": "Obsolete message. Tool is marked as obsolete when specified.",
      "type": "string"
    },
    "help": {
      "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
      "type": "string"
    },
    "nugetPackageId": {
      "description": "ID for the NuGet package.",
      "type": "string"
    },
    "npmPackageId": {
      "description": "ID for the NPM package.",
      "type": "string"
    },
    "aptgetPackageId": {
      "description": "ID for the AptGet package.",
      "type": "string"
    },
    "packageExecutable": {
      "description": "Exact name of the main executable found in the './tools' folder. Case-sensitive.",
      "type": "string"
    },
    "pathExecutable": {
      "description": "Exact name of the executable that can be found via 'where' or 'which'.",
      "type": "string"
    },
    "customExecutable": {
      "description": "Defines that locating the executable is implemented customly.",
      "type": "boolean"
    },
    "customLogger": {
      "description": "Enables custom logger.",
      "type": "boolean"
    },
    "tasks": {
      "description": "Help or introduction text to for the tool. Can contain HTML tags for better formatting.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "commonTaskProperties": {
      "description": "Common properties for all tasks.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Property"
      }
    },
    "commonTaskPropertySets": {
      "description": "Named common property sets which can be used by tasks.",
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "dataClasses": {
      "description": "Common used data classes.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/DataClass"
      }
    },
    "enumerations": {
      "description": "Used enumerations.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Enumeration"
      }
    },
    "_metadata": {
      "description": "Can be used to store additional information about the tool.",
      "type": "object",
      "additionalProperties": {
        "type": [
          "string",
          "number",
          "integer",
          "boolean",
          "object",
          "array"
        ]
      }
    }
  },
  "required": [
    "name",
    "officialUrl"
  ]
}

=== gruke-build/src/source/Nuke.Common/Tools/GitReleaseManager/GitReleaseManager.json
{
  "$schema": "https://raw.githubusercontent.com/gruke-build/src/master/source/Nuke.Tooling.Generator/schema.json",
  "references": [
    "https://raw.githubusercontent.com/GitTools/GitReleaseManager/develop/Source/GitReleaseManager.Cli/Options/BaseSubOptions.cs",
    "https://raw.githubusercontent.com/GitTools/GitReleaseManager/develop/Source/GitReleaseManager.Cli/Options/BaseGitHubSubOptions.cs",
    "https://raw.githubusercontent.com/GitTools/GitReleaseManager/develop/Source/GitReleaseManager.Cli/Options/AddAssetSubOptions.cs",
    "https://raw.githubusercontent.com/GitTools/GitReleaseManager/develop/Source/GitReleaseManager.Cli/Options/CloseSubOptions.cs",
    "https://raw.githubusercontent.com/GitTools/GitReleaseManager/develop/Source/GitReleaseManager.Cli/Options/CreateSubOptions.cs",
    "https://raw.githubusercontent.com/GitTools/GitReleaseManager/develop/Source/GitReleaseManager.Cli/Options/ExportSubOptions.cs",
    "https://raw.githubusercontent.com/GitTools/GitReleaseManager/develop/Source/GitReleaseManager.Cli/Options/PublishSubOptions.cs"
  ],
  "name": "GitReleaseManager",
  "officialUrl": "https://gitreleasemanager.readthedocs.io",
  "help": "GitReleaseManager is a tool that will help create a set of release notes for your application/product. It does this using the collection of issues which are stored on the GitHub Issue Tracker for your application/product.<para/>By inspecting the issues that have been assigned to a particular milestone, GitReleaseManager creates a set of release notes, in markdown format, which are then used to create a Release on GitHub.<para/>In addition to creating a Release, GitReleaseManager can be used to publish a release, close a milestone, and also to export the complete set of release notes for your application/product.",
  "nugetPackageId": "gitreleasemanager",
  "packageExecutable": "GitReleaseManager.exe",
  "tasks": [
    {
      "help": "Adds an asset to an existing release.",
      "postfix": "AddAssets",
      "definiteArgument": "addasset",
      "settingsClass": {
        "properties": [
          {
            "name": "AssetPaths",
            "type": "List<string>",
            "format": "--assets {value}",
            "separator": ",",
            "help": "Paths to the files to include in the release."
          },
          {
            "name": "TagName",
            "type": "string",
            "format": "--tagName {value}",
            "help": "The name of the release. Typically this is the generated SemVer Version Number."
          }
        ]
      }
    },
    {
      "help": "Closes the milestone.",
      "postfix": "Close",
      "definiteArgument": "close",
      "settingsClass": {
        "properties": [
          {
            "name": "Milestone",
            "type": "string",
            "format": "--milestone {value}",
            "help": "The milestone to use."
          }
        ]
      }
    },
    {
      "help": "Creates a draft release notes from a milestone.",
      "postfix": "Create",
      "definiteArgument": "create",
      "settingsClass": {
        "properties": [
          {
            "name": "AssetPaths",
            "type": "List<string>",
            "format": "--assets {value}",
            "separator": ",",
            "help": "Paths to the files to include in the release."
          },
          {
            "name": "TargetCommitish",
            "type": "string",
            "format": "--targetcommitish {value}",
            "help": "The commit to tag. Can be a branch or SHA. Defaults to repository's default branch."
          },
          {
            "name": "Milestone",
            "type": "string",
            "format": "--milestone {value}",
            "help": "The milestone to use."
          },
          {
            "name": "Name",
            "type": "string",
            "format": "--name {value}",
            "help": "The name of the release. Typically this is the generated SemVer Version Number."
          },
          {
            "name": "InputFilePath",
            "type": "string",
            "format": "--inputFilePath {value}",
            "help": "The path to the file to be used as the content of the release notes."
          },
          {
            "name": "Prerelease",
            "type": "bool",
            "format": "--prerelease",
            "help": "Creates the release as a pre-release."
          }
        ]
      }
    },
    {
      "help": "Exports all the Release Notes in markdown format.",
      "postfix": "Export",
      "definiteArgument": "export",
      "settingsClass": {
        "properties": [
          {
            "name": "TagName",
            "type": "string",
            "format": "--tagName {value}",
            "help": "The name of the release. Typically this is the generated SemVer Version Number."
          },
          {
            "name": "FileOutputPath",
            "type": "string",
            "format": "--fileOutputPath {value}",
            "help": "Path to the file export releases."
          }
        ]
      }
    },
    {
      "help": "Publishes the GitHub Release.",
      "postfix": "Publish",
      "definiteArgument": "publish",
      "settingsClass": {
        "properties": [
          {
            "name": "TagName",
            "type": "string",
            "format": "--tagName {value}",
            "help": "The name of the release. Typically this is the generated SemVer Version Number."
          }
        ]
      }
    }
  ],
  "commonTaskProperties": [
    {
      "name": "UserName",
      "type": "string",
      "format": "--username {value}",
      "help": "The username to access GitHub with."
    },
    {
      "name": "Password",
      "type": "string",
      "format": "--password {value}",
      "secret": true,
      "help": "The password to access GitHub with."
    },
    {
      "name": "RepositoryOwner",
      "type": "string",
      "format": "--owner {value}",
      "help": "The owner of the repository."
    },
    {
      "name": "RepositoryName",
      "type": "string",
      "format": "--repository {value}",
      "help": "The name of the repository."
    },
    {
      "name": "TargetDirectory",
      "type": "string",
      "format": "--targetDirectory {value}",
      "help": "The directory on which GitReleaseManager should be executed. Default is <em>current directory</em>."
    },
    {
      "name": "LogFilePath",
      "type": "string",
      "format": "--logFilePath {value}",
      "help": "Path to where log file should be created. Defaults is <em>logging to console</em>."
    },
    {
      "name": "Token",
      "type": "string",
      "format": "--token {value}",
      "secret": true,
      "help": "The access token to access GitHub with."
    }
  ]
}

=== gruke-build/src/source/Nuke.Common/Tools/InnoSetup/InnoSetup.json
{
  "$schema": "https://raw.githubusercontent.com/GreemDev/NUKE/master/source/Nuke.Tooling.Generator/schema.json",
  "references": [
    "http://www.jrsoftware.org/ishelp/index.php?topic=compilercmdline"
  ],
  "name": "InnoSetup",
  "officialUrl": "http://www.jrsoftware.org/isinfo.php",
  "help": "Inno Setup is a free installer for Windows programs by Jordan Russell and Martijn Laan. First introduced in 1997, Inno Setup today rivals and even surpasses many commercial installers in feature set and stability.",
  "pathExecutable": "iscc",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "ScriptFile",
            "type": "string",
            "format": "{value}",
            "position": 1,
            "help": "The .iss script file to compile"
          },
          {
            "name": "Output",
            "type": "bool",
            "format": "/O{value}",
            "customValue": true,
            "help": "Enable or disable output (overrides <c>Output</c>)"
          },
          {
            "name": "OutputDir",
            "type": "string",
            "format": "/O{value}",
            "help": "Output files to specified path (overrides <c>OutputDir</c>)"
          },
          {
            "name": "OutputBaseFilename",
            "type": "string",
            "format": "/F{value}",
            "help": "Overrides OutputBaseFilename with the specified filename"
          },
          {
            "name": "SignTools",
            "type": "Dictionary<string, string>",
            "format": "/S{key}={value}",
            "help": "Sets a SignTool with the specified name and command"
          },
          {
            "name": "Quiet",
            "type": "bool",
            "format": "/Q",
            "help": "Quiet compile (print error messages only)"
          },
          {
            "name": "QuietWithProgress",
            "type": "bool",
            "format": "/Qp",
            "help": "Enable quiet compile while still displaying progress"
          },
          {
            "name": "KeyValueDefinitions",
            "type": "Dictionary<string, string>",
            "format": "/D{key}={value}",
            "secret": false,
            "help": "Emulate <c>#define public {name} {value}</c>"
          },
          {
            "name": "KeyDefinitions",
            "type": "List<string>",
            "format": "/D{value}",
            "secret": false,
            "help": "Emulate <c>#define public {name}</c>"
          },
          {
            "name": "Verbosity",
            "type": "int",
            "format": "/V{value}",
            "help": "Emulate <c>#pragma verboselevel {number}</c> (highest level is 9)"
          }
        ]
      }
    }
  ]
}

=== gruke-build/src/source/Nuke.Common/Tools/VSTest/VSTest.json
{
  "$schema": "https://raw.githubusercontent.com/GreemDev/NUKE/master/source/Nuke.Tooling.Generator/schema.json",
  "references": [
    "https://msdn.microsoft.com/en-us/library/jj155796.aspx#//div[@class='content']"
  ],
  "name": "VSTest",
  "officialUrl": "https://msdn.microsoft.com/en-us/library/jj155796.aspx",
  "help": "VSTest.Console.exe is the command-line command that is used to run tests. You can specify several options in any order on the VSTest.Console.exe command line.",
  "nugetPackageId": "Microsoft.TestPlatform",
  "packageExecutable": "vstest.console.exe",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "TestAssemblies",
            "type": "List<string>",
            "format": "{value}",
            "position": 1,
            "help": "Run tests from the specified files. Separate multiple test file names with spaces."
          },
          {
            "name": "SettingsFile",
            "type": "string",
            "format": "/Settings:{value}",
            "help": "Run tests with additional settings such as data collectors."
          },
          {
            "name": "Tests",
            "type": "List<string>",
            "format": "/Tests:{value}",
            "separator": ",",
            "help": "Run tests with names that match the provided values. To provide multiple values, separate them by commas."
          },
          {
            "name": "Parallel",
            "type": "bool",
            "format": "/Parallel",
            "help": "Specifies that the tests be executed in parallel. By default up to all available cores on the machine may be used. The number of cores to use can be configured by using a settings file."
          },
          {
            "name": "EnableCodeCoverage",
            "type": "bool",
            "format": "/EnableCodeCoverage",
            "help": "Enables data diagnostic adapter CodeCoverage in the test run."
          },
          {
            "name": "InIsolation",
            "type": "bool",
            "format": "/InIsolation",
            "help": "Runs the tests in an isolated process."
          },
          {
            "name": "UseVsixExtensions",
            "type": "bool",
            "format": "/UseVsixExtensions:{value}",
            "help": "This makes vstest.console.exe process use or skip the VSIX extensions installed (if any) in the test run."
          },
          {
            "name": "TestAdapterPath",
            "type": "string",
            "format": "/TestAdapterPath:{value}",
            "help": "Forces the vstest.console.exe process to use custom test adapters from a specified path (if any) in the test run."
          },
          {
            "name": "Platform",
            "type": "VsTestPlatform",
            "format": "/Platform:{value}",
            "help": "Target platform architecture to be used for test execution."
          },
          {
            "name": "Framework",
            "type": "VsTestFramework",
            "format": "/Framework:{value}",
            "help": "Target .NET Framework version to be used for test execution."
          },
          {
            "name": "TestCaseFilters",
            "type": "List<string>",
            "format": "/TestCaseFilter:{value}",
            "separator": "|",
            "help": "Run tests that match the given expression.<para/><c>&lt;Expression&gt;</c> is of the format <c>&lt;property&gt;=&lt;value&gt;[|&lt;Expression&gt;]</c>.<para/>The <c>/TestCaseFilter</c> command line option cannot be used with the <c>/Tests</c> command line option.<para/>For information about creating and using expressions, see <a href=\"https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md\">TestCase filter</a>."
          },
          {
            "name": "Logger",
            "type": "string",
            "format": "/Logger:{value}",
            "help": "Specify a logger for test results. Example: To log results into a Visual Studio Test Results File (TRX) use <c>/Logger:trx</c>."
          },
          {
            "name": "ListTests",
            "type": "string",
            "format": "/ListTests:{value}",
            "help": "Lists discovered tests from the given test container."
          },
          {
            "name": "ListDiscoverers",
            "type": "bool",
            "format": "/ListDiscoverers",
            "help": "Lists installed test discoverers."
          },
          {
            "name": "ListExecutors",
            "type": "bool",
            "format": "/ListExecutors",
            "help": "Lists installed test executors."
          },
          {
            "name": "ListLoggers",
            "type": "bool",
            "format": "/ListLoggers",
            "help": "Lists installed test loggers."
          },
          {
            "name": "ListSettingsProviders",
            "type": "bool",
            "format": "/ListSettingsProviders",
            "help": "Lists installed test settings providers."
          },
          {
            "name": "DiagnosticsFile",
            "type": "string",
            "format": "/Diag:{value}",
            "help": "Writes diagnostic trace logs to the specified file."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "VsTestPlatform",
      "values": [
        "x86",
        "x64",
        "ARM"
      ]
    },
    {
      "name": "VsTestFramework",
      "values": [
        "Framework35",
        "Framework40",
        "Framework45"
      ]
    }
  ]
}
