=== gruke-build/src/source/Nuke.Tooling.Generator/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/gruke-build/src/master/source/Nuke.CodeGeneration/schema.json",
  "title": "Tool specification schema file by NUKE",
  "definitions": {
    "DataClass": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "Enumeration": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the enumeration.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "values": {
          "description": "The enumeration values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Enumeration is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name",
        "values"
      ]
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the property.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "type": {
          "description": "Type of the property. I.e., bool, int, string, List<int>, Dictionary<string, object>, Lookup<string, int.>",
          "type": "string"
        },
        "json": {
          "description": "Name used when serializing to JSON.",
          "type": "string"
        },
        "format": {
          "description": "Argument formatting for the property. '{value}' is replaced by the value of the property.",
          "type": "string"
        },
        "itemFormat": {
          "description": "Item formatting for dictionaries. '{key}' and '{value}' are replaced accordingly.",
          "type": "string"
        },
        "hidesBase": {
          "description": "Minimize compilation warnings by including a 'new' keyword on this definition.",
          "type": "boolean"
        },
        "noArgument": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "customImpl": {
          "description": "Custom implementation of the property.",
          "type": "boolean"
        },
        "separator": {
          "description": "Separator used for items of collection types.",
          "type": "string"
        },
        "disallowedCharacter": {
          "description": "Character that must be double-quoted.",
          "type": "string"
        },
        "quoteMultiple": {
          "description": "Specifies if list items should be double quoted.",
          "type": "boolean"
        },
        "default": {
          "description": "Default value that will be used if no value is given.",
          "type": "string"
        },
        "secret": {
          "description": "Specifies that the value is secret and should be hidden in output.",
          "type": "boolean"
        },
        "customValue": {
          "description": "Custom implementation of value presentation.",
          "type": "boolean"
        },
        "createOverload": {
          "description": "Specifies that an overload for the property should be created.",
          "type": "boolean"
        },
        "help": {
          "description": "Help text for the property.",
          "type": "string"
        },
        "delegates": {
          "description": "Dictionary delegates for named properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Property is marked as obsolete when specified.",
          "type": "string"
        },
        "onlyDelegates": {
          "type": "boolean"
        },
        "isTailArgument": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "SettingsClass": {
      "description": "The settings of the task.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "help": {
          "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
          "type": "string"
        },
        "postfix": {
          "description": "Postfix for the task alias.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "returnType": {
          "description": "Return type of the task.",
          "type": "string"
        },
        "omitCommonProperties": {
          "description": "Skips appending of common task properties.",
          "type": "boolean"
        },
        "commonPropertySets": {
          "description": "Appends the properties of the named property sets.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "preProcess": {
          "description": "Generates a pre-process hook",
          "type": "boolean"
        },
        "postProcess": {
          "description": "Generates a post-process hook",
          "type": "boolean"
        },
        "logLevelParsing": {
          "description": "Enables log level parsing",
          "type": "boolean"
        },
        "customStart": {
          "description": "Custom start implementation.",
          "type": "boolean"
        },
        "customAssertion": {
          "description": "Custom process assertion implementation.",
          "type": "boolean"
        },
        "definiteArgument": {
          "description": "Argument that will always be printed independently of any set property.",
          "type": "string"
        },
        "officialUrl": {
          "description": "Url of the task. If not specified, the tool url will be used.",
          "type": "string"
        },
        "settingsClass": {
          "$ref": "#/definitions/SettingsClass"
        },
        "deprecationMessage": {
          "description": "Obsolete message. Task is marked as obsolete when specified.",
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "references": {
      "description": "Contains all references on which this definition is based on. Allows checking for updates.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "imports": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "name": {
      "description": "Name of the Tool.",
      "type": "string",
      "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
    },
    "officialUrl": {
      "description": "Url to the official website.",
      "type": "string",
      "format": "uri"
    },
    "deprecationMessage": {
      "description": "Obsolete message. Tool is marked as obsolete when specified.",
      "type": "string"
    },
    "help": {
      "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
      "type": "string"
    },
    "nugetPackageId": {
      "description": "ID for the NuGet package.",
      "type": "string"
    },
    "npmPackageId": {
      "description": "ID for the NPM package.",
      "type": "string"
    },
    "aptgetPackageId": {
      "description": "ID for the AptGet package.",
      "type": "string"
    },
    "packageExecutable": {
      "description": "Exact name of the main executable found in the './tools' folder. Case-sensitive.",
      "type": "string"
    },
    "pathExecutable": {
      "description": "Exact name of the executable that can be found via 'where' or 'which'.",
      "type": "string"
    },
    "customExecutable": {
      "description": "Defines that locating the executable is implemented customly.",
      "type": "boolean"
    },
    "customLogger": {
      "description": "Enables custom logger.",
      "type": "boolean"
    },
    "tasks": {
      "description": "Help or introduction text to for the tool. Can contain HTML tags for better formatting.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "commonTaskProperties": {
      "description": "Common properties for all tasks.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Property"
      }
    },
    "commonTaskPropertySets": {
      "description": "Named common property sets which can be used by tasks.",
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "dataClasses": {
      "description": "Common used data classes.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/DataClass"
      }
    },
    "enumerations": {
      "description": "Used enumerations.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Enumeration"
      }
    },
    "_metadata": {
      "description": "Can be used to store additional information about the tool.",
      "type": "object",
      "additionalProperties": {
        "type": [
          "string",
          "number",
          "integer",
          "boolean",
          "object",
          "array"
        ]
      }
    }
  },
  "required": [
    "name",
    "officialUrl"
  ]
}

=== gruke-build/src/source/Nuke.Common/Tools/Squirrel/Squirrel.json
{
  "$schema": "https://raw.githubusercontent.com/GreemDev/NUKE/master/source/Nuke.Tooling.Generator/schema.json",
  "references": [
    "https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Update/Program.cs"
  ],
  "name": "Squirrel",
  "officialUrl": "https://github.com/Squirrel/Squirrel.Windows",
  "help": "Squirrel is both a set of tools and a library, to completely manage both installation and updating your Desktop Windows application, written in either C# or any other language (i.e., Squirrel can manage native C++ applications).",
  "nugetPackageId": "Squirrel.Windows",
  "packageExecutable": "Squirrel.exe",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "Install",
            "type": "string",
            "format": "--install={value}",
            "help": "Install the app whose package is in the specified directory."
          },
          {
            "name": "Uninstall",
            "type": "bool",
            "format": "--uninstall",
            "help": "Uninstall the app the same dir as Update.exe."
          },
          {
            "name": "Download",
            "type": "bool",
            "format": "--download",
            "help": "Download the releases specified by the URL and write new results to stdout as JSON."
          },
          {
            "name": "CheckForUpdate",
            "type": "bool",
            "format": "--checkForUpdate",
            "help": "Check for one available update and writes new results to stdout as JSON."
          },
          {
            "name": "Update",
            "type": "string",
            "format": "--update={value}",
            "help": "Update the application to the latest remote version specified by URL."
          },
          {
            "name": "Releasify",
            "type": "string",
            "format": "--releasify={value}",
            "help": "Update or generate a releases directory with a given NuGet package."
          },
          {
            "name": "CreateShortcut",
            "type": "string",
            "format": "--createShortcut={value}",
            "help": "Create a shortcut for the given executable name."
          },
          {
            "name": "RemoveShortcut",
            "type": "string",
            "format": "--removeShortcut={value}",
            "help": "Remove a shortcut for the given executable name."
          },
          {
            "name": "UpdateSelf",
            "type": "string",
            "format": "--updateSelf={value}",
            "help": "Copy the currently executing Update.exe into the default location."
          },
          {
            "name": "ProcessStart",
            "type": "string",
            "format": "--processStart={value}",
            "help": "Start an executable in the latest version of the app package."
          },
          {
            "name": "ProcessStartAndWait",
            "type": "string",
            "format": "--processStartAndWait={value}",
            "help": "Start an executable in the latest version of the app package."
          },
          {
            "name": "ReleaseDirectory",
            "type": "string",
            "format": "--releaseDir={value}",
            "help": "Path to a release directory to use with releasify."
          },
          {
            "name": "PackagesDirectory",
            "type": "string",
            "format": "--packagesDir={value}",
            "help": "Path to the NuGet Packages directory for C# apps."
          },
          {
            "name": "BootstrapperExecutable",
            "type": "string",
            "format": "--bootstrapperExe={value}",
            "help": "Path to the Setup.exe to use as a template."
          },
          {
            "name": "LoadingGif",
            "type": "string",
            "format": "--loadingGif={value}",
            "help": "Path to an animated GIF to be displayed during installation."
          },
          {
            "name": "Icon",
            "type": "string",
            "format": "--icon={value}",
            "help": "Path to an ICO file that will be used for icon shortcuts."
          },
          {
            "name": "SetupIcon",
            "type": "string",
            "format": "--setupIcon={value}",
            "help": "Path to an ICO file that will be used for the Setup executable's icon."
          },
          {
            "name": "SignWithParameters",
            "type": "string",
            "format": "--signWithParams={value}",
            "help": "Sign the installer via SignTool.exe with the parameters given."
          },
          {
            "name": "BaseUrl",
            "type": "string",
            "format": "--baseUrl={value}",
            "help": "Provides a base URL to prefix the RELEASES file packages with."
          },
          {
            "name": "ProcessStartArguments",
            "type": "string",
            "format": "--process-start-args={value}",
            "help": "Arguments that will be used when starting executable."
          },
          {
            "name": "ShortcutLocations",
            "type": "List<string>",
            "format": "--shortcut-locations={value}",
            "separator": ",",
            "help": "Comma-separated string of shortcut locations, e.g. 'Desktop,StartMenu'."
          },
          {
            "name": "GenerateNoMsi",
            "type": "bool",
            "format": "--no-msi",
            "help": "Don't generate an MSI package."
          },
          {
            "name": "GenerateNoDelta",
            "type": "bool",
            "format": "--no-delta",
            "help": "Don't generate delta packages to save time"
          },
          {
            "name": "FrameworkVersion",
            "type": "string",
            "format": "--framework-version={value}",
            "help": "Set the required .NET framework version, e.g. net461"
          }
        ]
      }
    }
  ]
}

=== gruke-build/src/source/Nuke.Common/Tools/WebConfigTransformRunner/WebConfigTransformRunner.json
{
  "$schema": "https://raw.githubusercontent.com/gruke-build/src/master/source/Nuke.Tooling.Generator/schema.json",
  "references": [
    "https://raw.githubusercontent.com/erichexter/WebConfigTransformRunner/master/Readme.md"
  ],
  "name": "WebConfigTransformRunner",
  "officialUrl": "https://github.com/erichexter/WebConfigTransformRunner",
  "help": "This is a commandline tool to run an ASP.Net web.config tranformation.",
  "nugetPackageId": "WebConfigTransformRunner",
  "packageExecutable": "WebConfigTransformRunner.exe",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "WebConfigFilename",
            "type": "string",
            "format": "{value}",
            "position": 1,
            "help": "The base web.config file"
          },
          {
            "name": "TransformFilename",
            "type": "string",
            "format": "{value}",
            "position": 2,
            "help": "The transformation web.config file"
          },
          {
            "name": "OutputFilename",
            "type": "string",
            "format": "{value}",
            "position": 3,
            "help": "The path to the output web.config file"
          }
        ]
      }
    }
  ]
}

=== gruke-build/src/source/Nuke.Common/Tools/DotnetPackaging/DotnetPackaging.json
{
  "$schema": "https://raw.githubusercontent.com/gruke-build/src/master/source/Nuke.Tooling.Generator/schema.json",
  "references": [
    "https://github.com/SuperJMN/DotnetPackaging/tree/master/src/DotnetPackaging.Console"
  ],
  "name": "DotnetPackaging",
  "officialUrl": "https://github.com/superjmn/dotnetpackaging",
  "help": "DotnetPackaging is able to package your application into various formats, including Deb and AppImage.",
  "nugetPackageId": "DotnetPackaging.Console",
  "packageExecutable": "DotnetPackaging.Console.dll",
  "tasks": [
    {
      "help": "Creates a Debian package from the specified directory.",
      "postfix": "Deb",
      "definiteArgument": "deb",
      "settingsClass": {
        "properties": [
          {
            "name": "Directory",
            "type": "string",
            "format": "--directory={value}",
            "help": "The input directory from which to create the package."
          },
          {
            "name": "Metadata",
            "type": "string",
            "format": "--metadata={value}",
            "help": "The metadata file to include in the package."
          },
          {
            "name": "Output",
            "type": "string",
            "format": "--output={value}",
            "help": "The output DEB file to create."
          }
        ]
      }
    },
    {
      "help": "Creates an AppImage package.",
      "postfix": "AppImage",
      "definiteArgument": "appimage",
      "settingsClass": {
        "properties": [
          {
            "name": "Directory",
            "type": "string",
            "format": "--directory={value}",
            "help": "The input directory from which to create the AppImage."
          },
          {
            "name": "Output",
            "type": "string",
            "format": "--output={value}",
            "help": "The output AppImage file to create."
          },
          {
            "name": "ApplicationName",
            "type": "string",
            "format": "--application-name={value}",
            "help": "The name of the application for the AppImage."
          },
          {
            "name": "MainCategory",
            "type": "DotnetPackagingMainCategory",
            "format": "--main-category {value}",
            "help": "Main category of the application."
          },
          {
            "name": "AdditionalCategories",
            "type": "List<DotnetPackagingAdditionalCategory>",
            "format": "--additional-categories {value}",
            "help": "Additional categories for the application."
          },
          {
            "name": "Icon",
            "type": "string",
            "format": "--icon {value}",
            "help": "The icon path for the application. When not provided, the tool looks up for an image called <c>AppImage.png</c>."
          },
          {
            "name": "Homepage",
            "type": "string",
            "format": "--homepage {value}",
            "help": "Home page of the application."
          },
          {
            "name": "License",
            "type": "string",
            "format": "--license {value}",
            "help": "License of the application."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "--version {value}",
            "help": "Version of the application."
          },
          {
            "name": "ScreenshotUrls",
            "type": "List<string>",
            "format": "--screenshot-urls {value}",
            "help": "URLs of screenshots of the application."
          },
          {
            "name": "Summary",
            "type": "string",
            "format": "--summary {value}",
            "help": "Short description of the application."
          },
          {
            "name": "AppId",
            "type": "string",
            "format": "--appId {value}",
            "help": "Application ID, usually a reverse DNS name like <c>com.SomeCompany.SomeApplication</c>."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "DotnetPackagingMainCategory",
      "values": [
        "AudioVideo",
        "Audio",
        "Video",
        "Development",
        "Education",
        "Game",
        "Graphics",
        "Network",
        "Office",
        "Settings",
        "Utility"
      ]
    },
    {
      "name": "DotnetPackagingAdditionalCategory",
      "values": [
        "Building",
        "Debugger",
        "IDE",
        "GUIDesigner",
        "Profiling",
        "RevisionControl",
        "Translation",
        "Calendar",
        "ContactManagement",
        "Database",
        "Dictionary",
        "Chart",
        "Email",
        "Finance",
        "FlowChart",
        "PDA",
        "ProjectManagement",
        "Presentation",
        "Spreadsheet",
        "WordProcessor",
        "TwoDGraphics",
        "VectorGraphics",
        "RasterGraphics",
        "ThreeDGraphics",
        "Scanning",
        "OCR",
        "Photography",
        "Publishing",
        "Viewer",
        "TextTools",
        "DesktopSettings",
        "HardwareSettings",
        "Printing",
        "PackageManager",
        "Dialup",
        "InstantMessaging",
        "Chat",
        "IRCClient",
        "FileTransfer",
        "HamRadio",
        "News",
        "P2P",
        "RemoteAccess",
        "Telephony",
        "TelephonyTools",
        "VideoConference",
        "WebBrowser",
        "WebDevelopment",
        "Midi",
        "Mixer",
        "Sequencer",
        "Tuner",
        "TV",
        "AudioVideoEditing",
        "Player",
        "Recorder",
        "DiscBurning",
        "ActionGame",
        "AdventureGame",
        "ArcadeGame",
        "BoardGame",
        "BlocksGame",
        "CardGame",
        "KidsGame",
        "LogicGame",
        "RolePlaying",
        "Simulation",
        "SportsGame",
        "StrategyGame",
        "Art",
        "Construction",
        "Music",
        "Languages",
        "Science",
        "ArtificialIntelligence",
        "Astronomy",
        "Biology",
        "Chemistry",
        "ComputerScience",
        "DataVisualization",
        "Economy",
        "Electricity",
        "Geography",
        "Geology",
        "Geoscience",
        "History",
        "ImageProcessing",
        "Literature",
        "Math",
        "NumericalAnalysis",
        "MedicalSoftware",
        "Physics",
        "Robotics",
        "Sports",
        "ParallelComputing",
        "Amusement",
        "Archiving",
        "Compression",
        "Electronics",
        "Emulator",
        "Engineering",
        "FileTools",
        "FileManager",
        "TerminalEmulator",
        "Filesystem",
        "Monitor",
        "Security",
        "Accessibility",
        "Calculator",
        "Clock",
        "TextEditor",
        "Documentation",
        "Core",
        "KDE",
        "GNOME",
        "GTK",
        "Qt",
        "Motif",
        "Java",
        "ConsoleOnly"
      ]
    }
  ]
}
